### ISSUE TITLE
Add "Generate Empty Dir" option

### ISSUE THREAD

**Issue by broshet44** [yodamad/svn2git#102]
Hello

As part of a migration with your tools, we had a problem on empty directories managed by SVN but not by git.
Svn-git has a "--preserve-empty-dirs" option to migrate them by placing a generic file.

Are there any plans to implement an option on your tool to use it?

**Comment by yodamad** [comment]
I'll check when getting back from holidays. Normally it's supported through configuration, I'll let you know quickly

**Comment by yodamad** [comment]
@broshet44 : u can do this by adding following option when lauching jar 

`java -jar svn2git.jar --application.flags.git-svn-clone-preserve-empty-dirs-option=true`

I'll see to add it on UI also

**Comment by yodamad** [comment]
Added in v1.22
