### ISSUE TITLE
Error: pathspec 'master' did not match any file(s) know to git

### ISSUE THREAD

**Issue by alexdu98** [yodamad/svn2git#115]
Hello,

I try to migrate a project but I get the same mistake each time (after several hours of processing).
My repository git is always empty and moreover I don't have the directory in temp what obliges me to start again all the git svn clone !

> 2020-12-06 03:56:51.608  INFO 14472 --- [-git-Executor-1] f.y.svn2git.service.HistoryManager       : Start step LIST_REMOVED_FILES
> 2020-12-06 03:56:51.608 DEBUG 14472 --- [-git-Executor-1] f.y.svn2git.aop.logging.LoggingAspect    : Exit: fr.yodamad.svn2git.service.HistoryManager.startStep() with result = MigrationHistory{id=999, step='LIST_REMOVED_FILES', status='RUNNING', date='2020-12-06T02:56:51.608Z', data=''}
> 2020-12-06 03:56:52.609 DEBUG 14472 --- [-git-Executor-1] fr.yodamad.svn2git.service.Cleaner       : Branch 0.31
> 2020-12-06 03:56:52.609 DEBUG 14472 --- [-git-Executor-1] fr.yodamad.svn2git.io.Shell              : Exec command : git checkout -b 0.31 origin/0.31
> 2020-12-06 03:56:52.609 DEBUG 14472 --- [-git-Executor-1] fr.yodamad.svn2git.io.Shell              : in C:\tmp\svn2git\20201205_185918_139\sisif
> 2020-12-06 03:56:56.348 DEBUG 14472 --- [-git-Executor-1] fr.yodamad.svn2git.io.Shell              : Exit : 0
> 2020-12-06 03:56:56.583 DEBUG 14472 --- [-git-Executor-1] fr.yodamad.svn2git.io.Shell              : Exec command : git checkout master
> 2020-12-06 03:56:56.599 DEBUG 14472 --- [-git-Executor-1] fr.yodamad.svn2git.io.Shell              : in C:\tmp\svn2git\20201205_185918_139\sisif
> 2020-12-06 03:56:57.610 DEBUG 14472 --- [-git-Executor-1] fr.yodamad.svn2git.io.Shell              : Exit : 1
> 2020-12-06 03:56:57.625 ERROR 14472 --- [-git-Executor-1] f.y.svn2git.aop.logging.LoggingAspect    : Exception in fr.yodamad.svn2git.service.Cleaner.listCleanedFiles() with cause = 'NULL' and exception = 'error: pathspec 'master' did not match any file(s) known to git

> java.lang.RuntimeException: error: pathspec 'master' did not match any file(s) known to git
>         at fr.yodamad.svn2git.io.Shell.execCommand(Shell.kt:92)
>         at fr.yodamad.svn2git.io.Shell.execCommand$default(Shell.kt:68)
>         at fr.yodamad.svn2git.service.Cleaner$listCleanedFiles$1.accept(Cleaner.kt:79)
>         at fr.yodamad.svn2git.service.Cleaner$listCleanedFiles$1.accept(Cleaner.kt:37)
>         at java.util.ArrayList.forEach(Unknown Source)
>         at fr.yodamad.svn2git.service.Cleaner.listCleanedFiles(Cleaner.kt:64)
>         at fr.yodamad.svn2git.service.Cleaner$$FastClassBySpringCGLIB$$6ac8d807.invoke(<generated>)
>         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
>         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
>         at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
>         at fr.yodamad.svn2git.aop.logging.LoggingAspect.logAround(LoggingAspect.java:85)
>         at sun.reflect.GeneratedMethodAccessor313.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.lang.reflect.Method.invoke(Unknown Source)
>         at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
>         at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
>         at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
>         at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
>         at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
>         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
>         at fr.yodamad.svn2git.service.Cleaner$$EnhancerBySpringCGLIB$$49f0ab65.listCleanedFiles(<generated>)
>         at fr.yodamad.svn2git.service.MigrationManager.startMigration(MigrationManager.kt:165)
>         at fr.yodamad.svn2git.service.MigrationManager$$FastClassBySpringCGLIB$$7876d7ce.invoke(<generated>)
>         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
>         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
>         at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
>         at java.util.concurrent.FutureTask.run(Unknown Source)
>         at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:68)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>         at java.lang.Thread.run(Unknown Source)

![image](https://user-images.githubusercontent.com/4395605/101278293-b7add680-37ba-11eb-8237-2150adc969be.png)
![image](https://user-images.githubusercontent.com/4395605/101278415-66eaad80-37bb-11eb-8e0c-b04a8f5e9fcc.png)

**Comment by yodamad** [comment]
Hi @alexdu98 

Thank for the feedback.
According to your configuration, I don't see where the problem can be. 

I see that you override trunk to be a specific branch but normally, it's not a problem.

Have u tried a smaller repo not to have to wait so long to check.

Maybe we can plan a quick jitsi call next week (sorry too busy this week) so that you can show me and help me give you the best support as possible ?

For the retry option, I've to work on it as it's not that easy to take in consideration all the use cases

**Comment by alexdu98** [comment]
Hi @yodamad,

I haven't had the problem on smaller repo's, but I don't know if it's a repo size problem or just a repo problem.

I used git svn clone directly for my 2 biggest repo, the migration is now complete.
So thank you for the proposal, but it is no longer necessary.
