### ISSUE TITLE
Error with custom SVN repo

### ISSUE THREAD

**Issue by spanishkangaroo** [yodamad/svn2git#143]
Hello,
first, let me tell me you that your app looks awesome.
I've been trying to use it to migrate some old SVN repos on a custom server to our new gitlab, but it seems the app is unable to find the folder structure for our repo, even when, afaik, it's an standard layout repo.

Please find some attached images with the subversion config and our actual svn repo layout.

[repo browser](https://ibb.co/XYD5c5D)

[svn configuration](https://ibb.co/VY3FK5b)

Regards,

**Comment by yodamad** [comment]
Hi

Thank you for feedback.
That's quite weird, as i've done tones of migrations without admin rights.

Maybe, I noticed that the protocol you're using in UI (svn://) is not the same than the one in tortoise.
You should try to use http in svn2git, this could resolve the issue.
