### ISSUE TITLE
Git version check doesn't work correctly

### ISSUE THREAD

**Issue by Nodwick** [yodamad/svn2git#164]
Using a portable git for windows via git-cmd. 2.46.0 should be > 2.20

`>git --version
git version 2.46.0.windows.1`

`>java -jar svn2git.jar
(...)
2024-08-29 13:34:15.226 ERROR 14260 --- [           main] fr.yodamad.svn2git.init.CheckUp          : ?? svn2git requires Git v2.20+ or newer`

**Comment by yodamad** [comment]
@Nodwick Thank you for feedback, I'll check that quickly

**Comment by yodamad** [comment]
@Nodwick : should be fixed in new release `2.4.3`
