### ISSUE TITLE
Gitlab project under group and subgroup

### ISSUE THREAD

**Issue by iMax-pp** [yodamad/svn2git#94]
- svn2git v1.18.1
- openjdk version "11.0.6"

When starting a migration, on GitLab information page, I cannot enter a group/subgroup (instead of just a group). The error message "Error checking Gitlab group." pops up when checking.

Reproduction steps:
- start a migration
- on GitLab information page, enter group/subgroup (like `titi/toto`)
- click on "Check"

**Comment by iMax-pp** [comment]
I tried other separators (like `_`, `.` or a whitespace), but none worked.

**Comment by yodamad** [comment]
Not supported yet ! :)
But good idea

**Comment by yodamad** [comment]
Supported in 1.20.x
