### ISSUE TITLE
Svn project having trunk under root

### ISSUE THREAD

**Issue by antoinegenot** [yodamad/svn2git#97]
### Environment
- svn2git v1.19.1
- java version 1.8.0_251

### Issue
When starting a migration, the migration failed at INIT step with the message : _Failed to create directory : The filename, directory name, or volume label syntax is incorrect._ 
Execution time : _17ms_
![image](https://user-images.githubusercontent.com/11257210/86954588-8ae78b80-c156-11ea-929b-f8068aa90c5f.png)

### Reproduction steps
- start a migration
- on SVN information page, choose the option "Or migrate full repository (assuming trunk, branches & tags are directly in root folder)"
- click on "Check"
- select trunk

**Comment by yodamad** [comment]
Cannot reproduce 😞

Can you add info : 
- OS ?
- repo name ?

**Comment by yodamad** [comment]
Also, you gitlab URL seems weird : 5384 ? normaly you need your group name not its ID

**Comment by yodamad** [comment]
@antoinegenot any input ? Thank you

**Comment by antoinegenot** [comment]
I manage to resolve the issue by changing partition used for executing the app (E: => C:)
FYI :
- OS : **Windows**
- repo name  : Which one ? the GIT repo or SVN repo ?
- 5384 is my gitlab subgroup id, when I check my subgroup using the name (corresponding to the subgroup Url) it is not working
